name: ci

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.4.0
    - name: Set up Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.22.1
    - name: Download dependencies
      run: go mod download
    - name: Cache modules
      uses: actions/cache@v2.1.6
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}    
    - name: Build
      run: go build
